### Variables
@baseUrl = http://localhost:3000
@apiUrl = {{baseUrl}}
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2OTkyMTQ5YTYwZWUxYWE0ZjA4ODlhYmQiLCJlbWFpbCI6InRlbWkuZGFyYW1vbGFAa2loYXNsLmNvbSIsInJvbGUiOiJtZXJjaGFudCIsImlhdCI6MTc3ODE0NzU4NiwiZXhwIjoxNzc4MzIwMzg2fQ.LtBJ291k0vT1drjz7B7fH999zHb5P_-3zrNJNiiPVIg
@invoiceId=69fc649d81c84c42143c27b4
@invoiceCustomerId=697018f2b9a77f1977fb7c5f
@invoiceStatus = auto


PUT {{apiUrl}}/invoices/{{invoiceId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "notes": "Updated notes for the invoice using auto -status",
   "status": "{{invoiceStatus}}"
}

### This will create a new version of the invoice (merchant-scoped)
